### ISSUE TITLE
Chat Packet doesn't work

### ISSUE THREAD

**Issue by timmytheman123** [NuroC/MooMoo.js#8]
whenever i run the chat packet from a command it doesn't work

    CommandManager.registerCommand(COMMAND_NAME_TEST, (Command, args) => {
            Command.reply(COMMAND_RESPONSE_TEST);
        chat("Example Text");
        });

i might just be using it wrong but it also doesn't work standalone

**Comment by NuroC** [comment]
Is that all of the code that you run? Obviously if you just copy pasted exactly that code into a userscript, it wont work because of the following reasons:
- variables `CommandManager`, `COMMAND_NAME_TEST`, `COMMAND_RESPONSE_TEST` are not defined.
- `chat` function is not defined
- The `Command.reply` function sends a chat message, and because of the chat cooldown the new chat you're trying to send is not being sent.

**Comment by timmytheman123** [comment]
oh ok it was probably the chat cooldown

i also did have everything defined
